### ISSUE TITLE
smh

### ISSUE THREAD

**Issue by 9tro** [SENPAi-03/SelfBot#1]
this is just alucard. you didn't even add anything new, just changed it from Alucard to SelfBot

**Comment by SENPAi-03** [comment]
> هذا مجرد alucard. لم تقم بإضافة أي شيء جديد ، فقط قمت بتغييره من Alucard إلى SelfBot

Nah check the main.py u'll see new things like embed rich presence etc...

**Comment by 9tro** [comment]
don't see a rich presence. it's not that hard to make anyways

**Comment by 9tro** [comment]
also. you just copied and pasted. you can tell, you didn't even import asyncio right. it says `bimport asyncio`

**Comment by SENPAi-03** [comment]
Anyway, I didn't uploaded it for the community
